/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#490013",
        "on-surface-variant": "#adaaab",
        "secondary-container": "#7c0599",
        "on-secondary-fixed": "#5b0072",
        "error-dim": "#d73357",
        "surface-variant": "#262627",
        "primary-fixed": "#ff7668",
        "primary": "#ff8e80",
        "error": "#ff6e84",
        "tertiary-dim": "#c085ed",
        "error-container": "#a70138",
        "surface-container-highest": "#262627",
        "on-primary-fixed": "#000000",
        "secondary": "#e67aff",
        "surface-tint": "#ff8e80",
        "on-primary": "#650003",
        "surface-container-low": "#131314",
        "outline": "#767576",
        "surface-container-high": "#1f1f21",
        "surface-container": "#19191b",
        "secondary-dim": "#dd72f7",
        "on-tertiary-fixed-variant": "#54197f",
        "on-secondary-container": "#f8c2ff",
        "on-primary-fixed-variant": "#610003",
        "tertiary-fixed-dim": "#c68af3",
        "on-primary-container": "#4f0002",
        "surface": "#0e0e0f",
        "tertiary": "#d7a0ff",
        "inverse-on-surface": "#565556",
        "on-secondary-fixed-variant": "#8417a1",
        "on-error-container": "#ffb2b9",
        "on-secondary": "#47005a",
        "primary-fixed-dim": "#ff5b4c",
        "on-tertiary": "#4f127a",
        "tertiary-fixed": "#d398ff",
        "surface-container-lowest": "#000000",
        "surface-dim": "#0e0e0f",
        "outline-variant": "#484849",
        "on-tertiary-fixed": "#290045",
        "on-tertiary-container": "#43006d",
        "background": "#0e0e0f",
        "tertiary-container": "#cb8ff9",
        "secondary-fixed": "#f7beff",
        "inverse-primary": "#c1000c",
        "secondary-fixed-dim": "#f2aaff",
        "surface-bright": "#2c2c2d",
        "primary-dim": "#e80f16",
        "primary-container": "#ff7668",
        "on-surface": "#ffffff",
        "inverse-surface": "#fcf8f9",
        "on-background": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Epilogue"],
        body: ["Manrope"],
        label: ["Space Grotesk"],
      },
    },
  },
  plugins: [],
}

